# -*- coding: utf-8 -*-
"""27_AddingTempDataToSignalDatafor256_SepsisOnset_ShockOnset_or_SepsisOnsetPlus31h_PatientsLessThan20%Missing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SOD3niHsG4Ta2LQ-TC6lo44XKgtDY8at
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
import pandas as pd
import io
import pandas as pd
from IPython.display import display
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
import os
import shutil
import posixpath
import urllib.request
import datetime
from collections import namedtuple



drive.mount('/content/gdrive')

df_all256_csvdata = pd.read_csv('/content/gdrive/My Drive/Master thesis/df_ts_records_all256SepsisPatients(lessThan20%Missing)_fromSepsisOnset_ShockOnset_or_sepsisOnsetPlus31h.csv')
df_all256_csvdata['TIME'] =  pd.to_datetime(df_all256_csvdata['TIME'])
print(df_all256_csvdata.shape) #(1431462, 10)

from google.colab import files
uploaded = files.upload()

df_ALL1056_tempdata = pd.read_csv(io.BytesIO(uploaded['df_All_1056_SepsisOnset_ShockOnset_OR_SepsisOnsetPlus31h_tempdata.csv']))

df_ALL1056_tempdata['CHARTTIME'] =  pd.to_datetime(df_ALL1056_tempdata['CHARTTIME']) #(50345, 4)
print(df_ALL1056_tempdata)

subject_ids_256 = df_all256_csvdata.SUBJECT_ID.unique()
print(subject_ids_256)
print(len(subject_ids_256))

df_all256_csvdata['TEMP'] = np.nan;

#subject_ids_404 = [40227]
#df_saf = df_all404_csvdata[df_all404_csvdata['SUBJECT_ID'] == 40227] #
#print(df_saf[['TIME','TEMP','HR']])#

for subject_id in subject_ids_256:
  df_all256_csvdata_subjectid = df_all256_csvdata[df_all256_csvdata['SUBJECT_ID'] == subject_id]
  for index, row in (df_ALL1056_tempdata[df_ALL1056_tempdata['SUBJECT_ID'] == subject_id]).iterrows():
    #print(row['CHARTTIME'],row['VALUE']) 
    try:
      df_all256_csvdata_index = df_all256_csvdata_subjectid.index[(df_all256_csvdata_subjectid['TIME'].dt.strftime('%Y-%m-%d %H:%M') == (row['CHARTTIME'].strftime('%Y-%m-%d %H:%M' ))) ]
      #print(df_all404_csvdata_index)
      df_all256_csvdata.loc[df_all256_csvdata_index,'TEMP'] = row['VALUE']
      
    except:
      print('Error occured when inserting temp data for SUBJECT_ID : '+ subject_id + 'for TIME : ' + row['CHARTTIME']);
    
    df_all256_csvdata_index = '';
    
  df_all256_csvdata_subjectid.drop(df_all256_csvdata_subjectid.index, inplace = True)
  print('TEMP data inserted successfuly for subject id : '+ str(subject_id)); 




"""

df_test.drop(df_test.index, inplace=True)

print('last time',charttime )
print('only last time minute', (datetime.datetime.strptime((charttime.strftime('%Y-%m-%d %H:%M' )), '%Y-%m-%d %H:%M')) )
df_test = df_all404_csvdata[df_all404_csvdata['SUBJECT_ID'] == 98930]
df_test = df_test.loc[3975:4000, :]
print('slice of dataframe to test')
print(df_test[['TIME','HR','RESP']])
print('applying date filter')
df_test = df_test[df_test['TIME'].dt.strftime('%Y-%m-%d %H:%M') == (charttime.strftime('%Y-%m-%d %H:%M' ))]
df_test_index = df_test.index[df_test['TIME'].dt.strftime('%Y-%m-%d %H:%M') == (charttime.strftime('%Y-%m-%d %H:%M' ))]

print('INDEX', df_test_index)
print(df_test[['TIME','HR','RESP','TEMP']])
print('ROW AFTER INDEX')
print(df_all404_csvdata.loc[df_test_index])

"""

"""
print(df_test['TIME'])
df_test = df_test['TIME'].dt.strftime('%Y-%m-%d %H:%M')
print('only minute dataframe data')
print(df_test)
"""
#df_test = pd.to_datetime(df_test['TIME'])
#print(df_test.loc[3975:4000, 'TIME'])

#print('filtering date')
#print(df_test[df_test['TIME'] == charttime])

pd.set_option('display.max_rows', 50000)
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 1000)
pd.set_option('max_colwidth', 800)

df_test_47275 = df_all256_csvdata[df_all256_csvdata['SUBJECT_ID']==47275]
print(df_test_47275[['TIME','TEMP','HR']])

# 79051

df_all256_csvdata.to_csv('df_ts_records_all256SepsisPatients(lessThan20%Missing)_fromSepsisOnset_ShockOnset_or_sepsisOnsetPlus31h_WITH_TEMP.csv', sep=',', index = False, header=True);

!cp "/content/df_ts_records_all256SepsisPatients(lessThan20%Missing)_fromSepsisOnset_ShockOnset_or_sepsisOnsetPlus31h_WITH_TEMP.csv" "/content/gdrive/My Drive/Master thesis"